from rf.login import login
from rf.get_model import get_model
from rf.get_firmware import get_firmware
from rf.get_memory_total import get_memory_total
from rf.get_disk_blob import get_disk_blob
from rf.get_disk_count import get_disk_count
from rf.get_disk_capacity import get_disk_capacity
from rf.get_uuid import get_uuid
from rf.get_network_adapters_blob import get_network_adapters_blob
from rf.get_nic_blob import get_nic_blob
from rf.reboot_server import reboot_server
from rf.set_hostname import set_hostname
from rf.enable_sriov import enable_sriov
from rf.set_dns import set_dns
from rf.set_timezone import set_timezone
from rf.set_license_key import set_license_key
from rf.set_power_options import set_power_options
from rf.get_cpu import get_cpu
from rf.get_bios import get_bios
from rf.get_tag import get_tag
from rf.get_status import get_status
from rf.get_nic_names import get_nic_names
