from rf.login import login
from rf.get_model import get_model
from rf.get_firmware import get_firmware
from rf.get_memory_total import get_memory_total
from rf.get_disk_blob import get_disk_blob
from rf.get_disk_count import get_disk_count
from rf.get_disk_capacity import get_disk_capacity
from rf.get_uuid import get_uuid
from rf.get_network_adapters_blob import get_network_adapters_blob
from rf.get_nic_blob import get_nic_blob
from rf.reboot_server import reboot_server
from rf.set_hostname import set_hostname
from rf.enable_sriov import enable_sriov
from rf.set_dns import set_dns
from rf.set_timezone import set_timezone
from rf.set_license_key import set_license_key
from rf.set_power_options import set_power_options
from rf.get_cpu import get_cpu
from rf.get_bios import get_bios
from rf.get_tag import get_tag
from rf.get_status import get_status
from rf.get_nic_names import get_nic_names
from rf.set_ntp import set_ntp
from rf.set_firmware import set_firmware
from rf.set_snmp import set_snmp
from rf.set_snmp_alerts import set_snmp_alerts
from rf.create_user import create_user
from rf.change_password import change_password
from rf.set_jitter import set_jitter
from rf.set_turbo import set_turbo
from rf.set_virtualization import set_virtualization
from rf.set_boot_order import set_boot_order
from rf.get_cpu_blob import get_cpu_blob
from rf.get_mem_blob import get_mem_blob
from rf.install_os import install_os
from rf.create_virtual_disks import create_virtual_disks
from rf.get_hostname import get_hostname
from rf.get_dns import get_dns
from rf.get_jitter import get_jitter
from rf.get_turbo import get_turbo
from rf.get_boot_order import get_boot_order
